#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : wrapt
Version  : 1.10.8
Release  : 20
URL      : https://pypi.python.org/packages/source/w/wrapt/wrapt-1.10.8.tar.gz
Source0  : https://pypi.python.org/packages/source/w/wrapt/wrapt-1.10.8.tar.gz
Summary  : Module for decorators, wrappers and monkey patching.
Group    : Development/Tools
License  : BSD-2-Clause
Requires: wrapt-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
wrapt
=====
|Travis| |Coveralls| |PyPI|
A Python module for decorators, wrappers and monkey patching.

%package python
Summary: python components for the wrapt package.
Group: Default

%description python
python components for the wrapt package.


%prep
%setup -q -n wrapt-1.10.8

%build
export LANG=C
export SOURCE_DATE_EPOCH=1484584833
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1484584833
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
